spring.application.name=erudite_node
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Postgres
spring.datasource.username=postgres
spring.datasource.password=Destructo123!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true